apiVersion: batch/v1
kind: CronJob
metadata:
  name: monitor
  namespace: turbomonitor
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 90
      template:
        spec:
          imagePullSecrets:
          - name: tivolinick-pull-secret
          containers:
          - name: turbomonitor
            image: quay.io/tivolinick/turbomonitor:0.1
            imagePullPolicy: Always
            command:
            - /scripts/test.sh
    #        env:
    #        - name: TURBOPASS
    #          valueFrom:
    #            secretKeyRef:
    #              name: actionscriptkeys
    #              key: turbopass
            volumeMounts:
            - mountPath: /kubeconfig
              name: kubeconfig
            - mountPath: /turbocreds
              name: turbocreds
            - mountPath: /monitorconfig
              name: monitorconfig
          volumes:
          - name: kubeconfig
            secret:
              secretName: kube-secret
          - name: turbocreds
            secret:
              secretName: turbo-creds
          - name: monitorconfig
            configMap:
              name: monitor-config
          restartPolicy: OnFailure
