apiVersion: batch/v1
kind: CronJob
metadata:
  name: monitor
  namespace: turbomonitor
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 90
      template:
        spec:
          containers:
          - name: turbomonitor
            image: quay.io/tivolinick/turbomonitor:0.1
            imagePullPolicy: Always
            command:
            - /scripts/test.sh
          restartPolicy: OnFailure
